runtime: java11
manual_scaling:
  instances: 1
entrypoint: "java -Dapp.home=/tmp/app_home -Dspring.profiles.active=gae -jar app.jar"
vpc_access_connector:
  name: "projects/cuba-sample-278518/locations/us-central1/connectors/gaef-connector"
